### ISSUE TITLE
Function works only when pull out of the package and loaded manualy 

### ISSUE THREAD

**Issue by HeymansAdrien** [MARSHAL-ROOT/marshal#2]
Hello,

When the function `getSUF` is called with `library(marshal)` the following error message appears  : 

> Error in \`[data.frame\`(x,i) : undefined columns selected

Although when I import the function into my directory and call it `source("R/getSUF.R")` ... it works.

**Comment by guillaumelobet** [comment]
Uhhh......

**Comment by HeymansAdrien** [comment]
The last update is great. The package works correctly. Thanks
